apiVersion: apps/v1
kind: Deployment
metadata:
  name: lezhang-playground
  labels:
    app: playground
spec:
  replicas: 1
  selector:
    matchLabels:
      app: playground
  template:
    metadata:
      labels:
        app: playground
    spec:
      containers:
      - name: playground
        image: wil42/playground:v1
        ports:
        - containerPort: 8888

---
apiVersion: v1
kind: Service
metadata:
  name: hzhou-playground
spec:
  selector:
    app: playground
  type: NodePort
  ports:
  - protocol: TCP
    port: 8888
    targetPort: 8888
    nodePort: 32222
